### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by Giaitzoglou** [ZinggJM/GxEPD#18]
Hi I was searching for a epaper signace with esp and I acame across your git can you please help with something , how do you send the pic files to the esp via WiFi connection to the router as a IP address by serial or as stantalone ap . 
Can you please explain me what your code does cause I am an rookie ?
Thanks in advance 
Chris giaitzoglou

**Comment by ZinggJM** [comment]
This question is outside the scope of my library. Such questions are best asked in the Arduino Forum Displays.
You may need to re-formulate your question to make it understandable more easily.
I am not a teacher and I know that documentation is not my strength. So I do not "explain" my code.
There is one example in my library that contains code I use in my IoT network. But my IoT webserver only sends texts, no pictures.
