### ISSUE TITLE
min and max broken on esp8266

### ISSUE THREAD

**Issue by cimba007** [ZinggJM/GxEPD#20]
Lots of errors since ESP-Core 2.4

https://pastebin.com/mifzNEjn

https://github.com/esp8266/Arduino/releases

**Remove min, max, isnan, isinf macros, use tempmlates from std:: instead.**

**Comment by ZinggJM** [comment]
I do not understand this issue, as I have replaced all min() and max() in my library.
I just tested once more with GxEPD_SPI_TestExample.
Do you use the actual version?

**Comment by cimba007** [comment]
Seems my version was outdated, thanks for fast reply!
