### ISSUE TITLE
ESP3266 + screen 2.13 waveshare

### ISSUE THREAD

**Issue by Malewsm** [ZinggJM/GxEPD#36]
Hi,

I am currently using your libraries with the e-paper screen 2.13 by waveshare. The setup works really good, but there is one issue I cannot overcome. When I use the simplest code, for instance, to print on the screen a simple text every 5 seconds - each time before the screen refreshes, it goes black/white/back a few times (even when the text is the same as previously). Is it possible to avoid this? So that the screen will just refresh letters which are different?

Thank you for your help in advance,
Mateusz 
```
// mapping suggestion from Waveshare SPI e-Paper to generic ESP8266
// BUSY -> GPIO4, RST -> GPIO2, DC -> GPIO0, CS -> GPIO15, CLK -> GPIO14, DIN -> GPIO13, GND -> GND, 3.3V -> 3.3V

#include <GxEPD.h>

// select the display class to use, only one

#include <GxGDEW0213Z16/GxGDEW0213Z16.cpp>  // 2.13" b/w/r
//#include <GxGDEW029Z10/GxGDEW029Z10.cpp>    // 2.9" b/w/r


#include GxEPD_BitmapExamples

// FreeFonts from Adafruit_GFX
#include <Fonts/FreeMonoBold9pt7b.h>
#include <Fonts/FreeMonoBold12pt7b.h>
#include <Fonts/FreeMonoBold18pt7b.h>
#include <Fonts/FreeMonoBold24pt7b.h>


#include <GxIO/GxIO_SPI/GxIO_SPI.cpp>
#include <GxIO/GxIO.cpp>

#if defined(ESP8266)

// GxIO_SPI(SPIClass& spi, int8_t cs, int8_t dc, int8_t rst = -1, int8_t bl = -1);
GxIO_Class io(SPI, SS, 0, 2); // arbitrary selection of D3(=0), D4(=2), selected for default of GxEPD_Class
// GxGDEP015OC1(GxIO& io, uint8_t rst = 2, uint8_t busy = 4);
GxEPD_Class display(io); // default selection of D4(=2), D2(=4)

#elif defined(ESP32)

// pins_arduino.h, e.g. LOLIN32
//static const uint8_t SS    = 5;
//static const uint8_t MOSI  = 23;
//static const uint8_t MISO  = 19;
//static const uint8_t SCK   = 18;

// GxIO_SPI(SPIClass& spi, int8_t cs, int8_t dc, int8_t rst = -1, int8_t bl = -1);
GxIO_Class io(SPI, SS, 17, 16); // arbitrary selection of 17, 16
// GxGDEP015OC1(GxIO& io, uint8_t rst = D4, uint8_t busy = D2);
GxEPD_Class display(io, 16, 4); // arbitrary selection of (16), 4

#elif defined(ARDUINO_ARCH_SAMD)


GxIO_Class io(SPI, 4, 7, 6);
GxEPD_Class display(io, 6, 5);

#elif defined(_BOARD_GENERIC_STM32F103C_H_)

// GxIO_SPI(SPIClass& spi, int8_t cs, int8_t dc, int8_t rst = -1, int8_t bl = -1);
GxIO_Class io(SPI, SS, 3, 2);
// GxGDEP015OC1(GxIO& io, uint8_t rst = 9, uint8_t busy = 7);
GxEPD_Class display(io, 2, 1);

#else

// pins_arduino.h, e.g. AVR
//#define PIN_SPI_SS    (10)
//#define PIN_SPI_MOSI  (11)
//#define PIN_SPI_MISO  (12)
//#define PIN_SPI_SCK   (13)

GxIO_Class io(SPI, SS, 8, 9); // arbitrary selection of 8, 9 selected for default of GxEPD_Class
GxEPD_Class display(io);

#endif


void setup()
{
  Serial.begin(115200);
  Serial.println();
  Serial.println("setup");

  display.init();

  Serial.println("setup done");
   


}
int t=0;
void loop()
{
// void eraseDisplay();
  const char* name = "FreeMonoBold9pt7b";
  const GFXfont* f = &FreeMonoBold12pt7b;
  display.fillScreen(GxEPD_WHITE);
  display.setTextColor(GxEPD_BLACK);
  display.setFont(f);
//  display.setRotation(45);
  display.setCursor(0, 0);
  display.println();
  display.println(t);
  t=t+1;

display.update();


  delay(2000);
}
```

**Comment by ZinggJM** [comment]
> please use the Arduino Forum Displays for questions or enhancement suggestions

Please observe the guide in the issue_template.md.

This is **not** an issue of the library, but physical behavior of the e-paper display.
Black / white e-paper displays can support fast update for partial update, applying only the difference.
For this the controller internally has 2 buffers and uses a waveform table for partial update that handles only the differences. For 3-color e-paper displays this is not possible because of the physical process; the movement speed difference of the smaller black particles and the larger colored particles is used, which does not work using only differences, and the 2 buffers are used for black and colored.

**Comment by G6EJD** [comment]
Epaper displays are really designed for updates occasionally not every 5-secs and they take a long time to refresh flashing many tines so what your seeing is completely normal. You need to rethink how frequently you update the display. Welcome to epaper displays and remember they take no power after refresh/update!

**Comment by Malewsm** [comment]
Hey,   Thank you for your answer! Hmm, but in the project, I am working right now it is necessary to eliminate this flickering. It is possible with smaller screens! Is it a feature which somehow I can modify in software?   Thank you for your help,  Mateusz M  
                
              
               
                 
                  Dnia 28 marca 2018 19:00 G6EJD &lt;notifications@github.com&gt; napisał(a):
                 
                 
                   Epaper displays are really designed for updates occasionally not every 5-secs and they take a long time to refresh flashing many tines so what your seeing is completely normal. You need to rethink how frequently you update the display. Welcome to epaper displays and remember they take no power after refresh/update!

**Comment by ZinggJM** [comment]
Search for "RGB e-paper", google finds. True RGB e-paper displays physically work like b/w e-paper, and thus can be fast as these. If you get me such a display, I will try to make a library for it.

**Comment by G6EJD** [comment]
The smaller screen (1.54") is fast, about the same as the 2.9". If you want to get fast screen refresh times then an e-paper is not your solution. There are no software fixes you can apply as the screen delay is a physical limitation until the technology improves (if ever).

**Comment by ZinggJM** [comment]
The main difference however is between b/w and 3-color e-paper displays. Waveshare has published a table with update times for all SPI e-papers they sell (on the page for the e-paper HAT).
And according to this table only the small b/w displays support partial update (without flashing).
