### ISSUE TITLE
Support for PaPiRus HAT Display

### ISSUE THREAD

**Issue by Donderda** [ZinggJM/GxEPD#41]
can you tell me whether this lib supports the PaPiRus HAT Display (see https://github.com/PiSupply/PaPiRus/)?

 In those repos I found this document: https://github.com/PiSupply/PaPiRus/blob/master/hardware/PaPiRus%20HAT/Latest%20Version%20-%20v1.9/4P018-00_03_G2_Aurora%20Mb_COG_Driver_Interface_Timing_for_small%2Bsize_2015....pdf
Does this help?

To be more precise: I want to run the 2.7" Display on a PaPiRus v1.9 board with an Arduino UNO. I was able to connect it and clearing its display, but I can't draw anything because the UNO has not enough RAM. I found your lib and as far as I understand your lib could be able to bypass the RAM problem?

Any reply would be appreciated. :)

**Comment by ZinggJM** [comment]
Please observe the rules I set in issue_template.md.
I do not like to get issues just for asking questions.
My library supports e-paper display panels from Dalian Good Display.
The Pervasive e-paper displays are totally different and not supported by GxEPD and never will be.
The new library GxEPD2 (under construction) shows how the functionality of GxEPD can be added to basic e-paper driver classes. 
This could be a starting point for what you need.
