### ISSUE TITLE
how to create 3 color images

### ISSUE THREAD

**Issue by yene** [ZinggJM/GxEPD#47]
Hi,

how did you make the three color bitmaps.
I used this tool for black/white images http://javl.github.io/image2cpp/, it is very good for that.
But three color images I could not get it to work.

thank you for your help

**Comment by ZinggJM** [comment]
I didn't. The bitmap examples are taken from the demo code of Good Display and Waveshare. Waveshare has Wiki pages for their displays, and a link to a downloadable image2lcd. Most example bitmaps consist of 2 monochrome bitmaps, one for b/w, one for color/white.

This is not an issue of this library. Please post questions in the Arduino Forum Displays.
