### ISSUE TITLE
Sleep in 1.54 inch BW epap display

### ISSUE THREAD

**Issue by num19** [ZinggJM/GxEPD#53]
I have read datasheet of that display and I want to ask why these lines doesn't correspond with datasheet commands for sleep.
`void GxGDEP015OC1::_PowerOff(void)
{
  _writeCommand(0x22);
  _writeData(0xc3);
  _writeCommand(0x20);
  _waitWhileBusy("_PowerOff", power_off_time);
}`

**Comment by ZinggJM** [comment]
Closed, because the issue template has not been obeyed. This is a question, not an issue!
