### ISSUE TITLE
Partial Refresh?

### ISSUE THREAD

**Issue by novusabeo** [ZinggJM/GxEPD#55]
### Version number of the library used, should be the current one
Using Current Library

### Powered from TTGO ESP32 Board To Drive

**Comment by ZinggJM** [comment]
**version number is required for reference (history)!** Actual version is 2.3.16
Partial update works with my GDEW029Z10, only the window part is updated and "flashes".
3-color displays physically can't support "fast partial update" aka differential update.

**Comment by novusabeo** [comment]
Oh I see. Thank you.

**Comment by novusabeo** [comment]
What if I was to code it as if it was just a b/w display?? Say the GxGDEH029A1?

**Comment by ZinggJM** [comment]
**please observe the issue template!** the issue is closed, and issues in GxEPD **are not to be used** for discussions.
