### ISSUE TITLE
bitmap issue

### ISSUE THREAD

**Issue by nautilus087** [ZinggJM/GxEPD#61]
Hi,
i have tried your code Wifi_espe32_ink and it works well, but when I upload your bmp (like: first200x200.bmp) on my Apache server i get this error on console: 

HTTP/1.1 200 OK
headers received
loaded in 735 ms
bitmap format not handled.

What's the difference between normal Apache server and raw.githubusercontent.com?

Thank you

**Comment by ZinggJM** [comment]
Why do you think this is an issue with this library? See issue_template.md!
Most likely your server uses http protocol, not https.
