### ISSUE TITLE
Support for ESP-IDF framework

### ISSUE THREAD

**Issue by andrzejtokarski** [ZinggJM/GxEPD#62]
Hello! 
Thank you for an amazing library. Did you consider adding official support for ESP-IDF framework? I'm building the project using platformio and targeting ESP32. I see that you already separated SPI connectivity but the library sill depends on Adafruit_GFX.h.

**Comment by ZinggJM** [comment]
Hello,

Thank you for your interest in this library.

But this is a question and **not an issue** of this library. I worte an issue_template.md!

I have considered this, but the answer is no for the near future. I don't have the capacitiy.
GxEPD and GxEPD2 will always depend on Adafruit_GFX. I might consider a variant using an Adafruit_GFX clone, but Adafruit_GFX is evolving, and the clone would loose that.
I intend to learn to use additional platforms, such as platformio, or right now particle.io, but I have learnt that I first need to get some experience on a new platform before porting any library to it.

**Comment by andrzejtokarski** [comment]
Thank you for the answer, sorry for polluting the issues.
