### ISSUE TITLE
Lib not found by Arduino IDE

### ISSUE THREAD

**Issue by hadmut** [ZinggJM/GxEPD#65]
Hi, 
some source codes and examples available for different epaper boards require GxEPD, but the arduino IDE finds only GxEPD2. 

Furthermore, it's not obvious and not directly comprehensible what's the difference between GxEPD (Version 3) and GxEPD2 (Version 1), which is newer/better/the one to use.

**Comment by ZinggJM** [comment]
GxEPD can be downloaded as ZIP-file, and can be added to the Arduino IDE by the Library Manager with the Add ZIP-File method. **So this is not an issue of this library.**

GxEPD2 is newer and easier to use, in my opinion, but maybe not yet be as stable and widely used as GxEPD. But GxEPD2 should be used for new projects.
