### ISSUE TITLE
where is GxGDE0213B72.h ?

### ISSUE THREAD

**Issue by coolty** [ZinggJM/GxEPD#66]
Where is GxGDE0213B72.h? Many projects reference this specific repo and mention this file, but it's not in this repo. Where did it go?

**Comment by G6EJD** [comment]
That version is specifically from: https://github.com/lewisxhe/TTGO-Electronic-Badge
the prolithic copier of others code often without recognition of the author.

**Comment by coolty** [comment]
Well it's not on that repo either and it tells us to use your repo for
those files.. were they removed from the repo?

**Comment by ZinggJM** [comment]
From README.md:
> ### I can and will only support e-paper panels I have!
- promotion panels from suppliers are welcome, to add support to GxEPD
- donation panels from users are welcome, to add support to GxEPD

I don't have that display, and the file mentioned was never part of my library.
I should get that e-paper soon from Good Display, as the original 2.31" b/w is no longer available.
I will then ad **my** version to my libraries.

@coolty 
You should do some search and background check before opening such an issue!

**There are so many forks of this library; I can't have an overview of who added what to his version.**
