### ISSUE TITLE
Impossible to use GxEPD_DARKGREY  or GxEPD_LIGHTGREY with GDEW042T2 

### ISSUE THREAD

**Issue by Vxs14** [ZinggJM/GxEPD#70]
in GxGDEW042T2.cpp there is the definition of the two gray scale, but no result with all the Graphics Primitives.

Maybe i make wrong ? 

// the only colors supported by any of these displays; mapping of other colors is class specific
#define GxEPD_BLACK     0x0000
#define GxEPD_DARKGREY  0x7BEF      /* 128, 128, 128 */
#define GxEPD_LIGHTGREY 0xC618      /* 192, 192, 192 */
#define GxEPD_WHITE     0xFFFF
#define GxEPD_RED       0xF800      /* 255,   0,   0 */

**Comment by ZinggJM** [comment]
These definitions are in GxEPD.h. GDEW042T2 does not support grey levels.
The definitions most likely are leftovers from an earlier version, where support of DESTM32-L for parallel IF e-papers with grey levels was part of GxEPD, now in GxEPD_HD.
GxEPD does not support grey levels (GxEPD2 supports bitmaps with grey level on some panels with grey levels through drawNative() ).
