### ISSUE TITLE
Open bmp from sd card

### ISSUE THREAD

**Issue by amittel** [ZinggJM/GxEPD#8]
Hi!
Would it be possible to open a bmp from a sd-card and display it?

I found this [example](https://github.com/esp8266/Basic/blob/master/libraries/Adafruit_ILI9341/examples/spitftbitmap/spitftbitmap.ino) using a ILI9341.

Could I just convert it to use it with your lib?

**Comment by ZinggJM** [comment]
It would be possible, but I do not plan to do so.
The GxEPD library can be used as a starting point, as an example; an experienced user can copy and modify it to his needs. Or even clone it on GitHub.
Or you can start all over, starting from example code from Dalian Good Display or Waveshare.
